In [1]:
import pandas as pd
import numpy as np
import data_preprocess as dp

In [2]:
id_df = pd.read_csv('../data/processed data/id_list.csv',index_col=0)
id_list = id_df['location_id']
id_list

3        4
9       24
12      12
13      13
40      41
      ...
246    244
248    246
251    249
261    261
262    262
Name: location_id, Length: 66, dtype: int64

In [3]:
# get a wohle years data in manhattan
data_path_list = [
  '../data/raw data/yellow_tripdata_2022-01.parquet',
  # '../data/raw data/yellow_tripdata_2022-02.parquet',
  # '../data/raw data/yellow_tripdata_2022-03.parquet',
  # '../data/raw data/yellow_tripdata_2022-04.parquet',
  # '../data/raw data/yellow_tripdata_2022-05.parquet',
  # '../data/raw data/yellow_tripdata_2022-06.parquet',
  # '../data/raw data/yellow_tripdata_2022-07.parquet',
  # '../data/raw data/yellow_tripdata_2022-08.parquet',
  # '../data/raw data/yellow_tripdata_2022-09.parquet',
  # '../data/raw data/yellow_tripdata_2022-10.parquet',
  # '../data/raw data/yellow_tripdata_2022-11.parquet',
  # '../data/raw data/yellow_tripdata_2022-12.parquet'
]
start_time = pd.to_datetime('2022/01/01')
end_time = pd.to_datetime('2022/01/14')
m_tripdata = dp.get_tripdata(data_path_list, id_list, start_time, end_time)
m_tripdata

,index,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,...,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee,count,month,date,day,hour
0,0,1,2022-01-01 00:35:40,2022-01-01 00:53:29,2.0,3.80,1.0,N,142,236,...,0.0,0.3,21.95,2.5,0.0,1,1,2022-01-01,6,0
1,1,1,2022-01-01 00:33:43,2022-01-01 00:42:07,1.0,2.10,1.0,N,236,42,...,0.0,0.3,13.30,0.0,0.0,1,1,2022-01-01,6,0
2,2,2,2022-01-01 00:53:21,2022-01-01 01:02:19,1.0,0.97,1.0,N,166,166,...,0.0,0.3,10.56,0.0,0.0,1,1,2022-01-01,6,0
3,3,2,2022-01-01 00:25:21,2022-01-01 00:35:23,1.0,1.09,1.0,N,114,68,...,0.0,0.3,11.80,2.5,0.0,1,1,2022-01-01,6,0
4,4,2,2022-01-01 00:36:48,2022-01-01 01:14:20,1.0,4.30,1.0,N,68,163,...,0.0,0.3,30.30,2.5,0.0,1,1,2022-01-01,6,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
802201,2414455,2,2022-01-13 23:14:15,2022-01-13 23:28:46,NaN,4.42,NaN,None,113,236,...,0.0,0.3,26.82,NaN,NaN,1,1,2022-01-13,4,23
802202,2414456,2,2022-01-13 23:15:40,2022-01-13 23:19:51,NaN,0.86,NaN,None,249,234,...,0.0,0.3,13.05,NaN,NaN,1,1,2022-01-13,4,23
802203,2414457,2,2022-01-13 23:09:00,2022-01-13 23:26:00,NaN,4.55,NaN,None,100,13,...,0.0,0.3,24.21,NaN,NaN,1,1,2022-01-13,4,23
802204,2414459,2,2022-01-13 23:06:59,2022-01-13 23:15:50,NaN,1.84,NaN,None,90,170,...,0.0,0.3,15.61,NaN,NaN,1,1,2022-01-13,4,23
802205,2414462,1,2022-01-13 23:37:30,2022-01-13 23:47:19,NaN,2.80,NaN,None,261,107,...,0.0,0.3,17.16,NaN,NaN,1,1,2022-01-13,4,23

In [5]:
def od_construct(tripdata,start_time, end_time):
  hour_count = tripdata.groupby(['PULocationID','DOLocationID','date','day','hour']).agg({'count':'sum'})
  hour_count = hour_count.reset_index(drop=False)
  grouped = hour_count.groupby(['date', 'hour'])
  temp_adj_dict = {}
  adj_dict = {}
  for group_name, group_data in grouped:
    adjacency_matrix = np.zeros((len(id_list), len(id_list)))
    id_mapping = {location: idx for idx, location in enumerate(id_list.values)}
    for _, row in group_data.iterrows():
        pu_location = id_mapping[row['PULocationID']]
        do_location = id_mapping[row['DOLocationID']]
        count = row['count']
        adjacency_matrix[pu_location][do_location] = count
    temp_adj_dict[group_name] = adjacency_matrix
  date_range = pd.date_range(start_time,end_time)
  key_to_check_list = []
  for date in date_range:
    for h in range(0,24):
      key_to_check_list.append((date.date(),h))
  for k in key_to_check_list:
    if k not in temp_adj_dict.keys():
      adj_dict[k] = np.zeros((len(id_list), len(id_list)))
    else:
      adj_dict[k] = temp_adj_dict[k]
  return adj_dict

In [10]:
od_adj = od_construct(m_tripdata,'2022-01-01','2022-01-14')

In [11]:
od_adj[(pd.to_datetime('2022-01-01').date(),12)]

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 3.]])

In [12]:
len(od_adj.keys())

336

In [13]:
for t,v in od_adj.items():
    print(t)

(datetime.date(2022, 1, 1), 0)
(datetime.date(2022, 1, 1), 1)
(datetime.date(2022, 1, 1), 2)
(datetime.date(2022, 1, 1), 3)
(datetime.date(2022, 1, 1), 4)
(datetime.date(2022, 1, 1), 5)
(datetime.date(2022, 1, 1), 6)
(datetime.date(2022, 1, 1), 7)
(datetime.date(2022, 1, 1), 8)
(datetime.date(2022, 1, 1), 9)
(datetime.date(2022, 1, 1), 10)
(datetime.date(2022, 1, 1), 11)
(datetime.date(2022, 1, 1), 12)
(datetime.date(2022, 1, 1), 13)
(datetime.date(2022, 1, 1), 14)
(datetime.date(2022, 1, 1), 15)
(datetime.date(2022, 1, 1), 16)
(datetime.date(2022, 1, 1), 17)
(datetime.date(2022, 1, 1), 18)
(datetime.date(2022, 1, 1), 19)
(datetime.date(2022, 1, 1), 20)
(datetime.date(2022, 1, 1), 21)
(datetime.date(2022, 1, 1), 22)
(datetime.date(2022, 1, 1), 23)
(datetime.date(2022, 1, 2), 0)
(datetime.date(2022, 1, 2), 1)
(datetime.date(2022, 1, 2), 2)
(datetime.date(2022, 1, 2), 3)
(datetime.date(2022, 1, 2), 4)
(datetime.date(2022, 1, 2), 5)
(datetime.date(2022, 1, 2), 6)
(datetime.date(2022, 1, 2), 7)
(datetime.date(2022, 1, 2), 8)
(datetime.date(2022, 1, 2), 9)
(datetime.date(2022, 1, 2), 10)
(datetime.date(2022, 1, 2), 11)
(datetime.date(2022, 1, 2), 12)
(datetime.date(2022, 1, 2), 13)
(datetime.date(2022, 1, 2), 14)
(datetime.date(2022, 1, 2), 15)
(datetime.date(2022, 1, 2), 16)
(datetime.date(2022, 1, 2), 17)
(datetime.date(2022, 1, 2), 18)
(datetime.date(2022, 1, 2), 19)
(datetime.date(2022, 1, 2), 20)
(datetime.date(2022, 1, 2), 21)
(datetime.date(2022, 1, 2), 22)
(datetime.date(2022, 1, 2), 23)
(datetime.date(2022, 1, 3), 0)
(datetime.date(2022, 1, 3), 1)
(datetime.date(2022, 1, 3), 2)
(datetime.date(2022, 1, 3), 3)
(datetime.date(2022, 1, 3), 4)
(datetime.date(2022, 1, 3), 5)
(datetime.date(2022, 1, 3), 6)
(datetime.date(2022, 1, 3), 7)
(datetime.date(2022, 1, 3), 8)
(datetime.date(2022, 1, 3), 9)
(datetime.date(2022, 1, 3), 10)
(datetime.date(2022, 1, 3), 11)
(datetime.date(2022, 1, 3), 12)
(datetime.date(2022, 1, 3), 13)
(datetime.date(2022, 1, 3), 14)
(datetime.date(2022, 1, 3), 15)
(datetime.date(2022, 1, 3), 16)
(datetime.date(2022, 1, 3), 17)
(datetime.date(2022, 1, 3), 18)
(datetime.date(2022, 1, 3), 19)
(datetime.date(2022, 1, 3), 20)
(datetime.date(2022, 1, 3), 21)
(datetime.date(2022, 1, 3), 22)
(datetime.date(2022, 1, 3), 23)
(datetime.date(2022, 1, 4), 0)
(datetime.date(2022, 1, 4), 1)
(datetime.date(2022, 1, 4), 2)
(datetime.date(2022, 1, 4), 3)
(datetime.date(2022, 1, 4), 4)
(datetime.date(2022, 1, 4), 5)
(datetime.date(2022, 1, 4), 6)
(datetime.date(2022, 1, 4), 7)
(datetime.date(2022, 1, 4), 8)
(datetime.date(2022, 1, 4), 9)
(datetime.date(2022, 1, 4), 10)
(datetime.date(2022, 1, 4), 11)
(datetime.date(2022, 1, 4), 12)
(datetime.date(2022, 1, 4), 13)
(datetime.date(2022, 1, 4), 14)
(datetime.date(2022, 1, 4), 15)
(datetime.date(2022, 1, 4), 16)
(datetime.date(2022, 1, 4), 17)
(datetime.date(2022, 1, 4), 18)
(datetime.date(2022, 1, 4), 19)
(datetime.date(2022, 1, 4), 20)
(datetime.date(2022, 1, 4), 21)
(datetime.date(2022, 1, 4), 22)
(datetime.date(2022, 1, 4), 23)
(datetime.date(2022, 1, 5), 0)
(datetime.date(2022, 1, 5), 1)
(datetime.date(2022, 1, 5), 2)
(datetime.date(2022, 1, 5), 3)
(datetime.date(2022, 1, 5), 4)
(datetime.date(2022, 1, 5), 5)
(datetime.date(2022, 1, 5), 6)
(datetime.date(2022, 1, 5), 7)
(datetime.date(2022, 1, 5), 8)
(datetime.date(2022, 1, 5), 9)
(datetime.date(2022, 1, 5), 10)
(datetime.date(2022, 1, 5), 11)
(datetime.date(2022, 1, 5), 12)
(datetime.date(2022, 1, 5), 13)
(datetime.date(2022, 1, 5), 14)
(datetime.date(2022, 1, 5), 15)
(datetime.date(2022, 1, 5), 16)
(datetime.date(2022, 1, 5), 17)
(datetime.date(2022, 1, 5), 18)
(datetime.date(2022, 1, 5), 19)
(datetime.date(2022, 1, 5), 20)
(datetime.date(2022, 1, 5), 21)
(datetime.date(2022, 1, 5), 22)
(datetime.date(2022, 1, 5), 23)
(datetime.date(2022, 1, 6), 0)
(datetime.date(2022, 1, 6), 1)
(datetime.date(2022, 1, 6), 2)
(datetime.date(2022, 1, 6), 3)
(datetime.date(2022, 1, 6), 4)
(datetime.date(2022, 1, 6), 5)
(datetime.date(2022, 1, 6), 6)
(datetime.date(2022, 1, 6), 7)
(datetime.date(2022, 1, 6), 8)
(datetime.date(2022, 1, 6), 9)
(datetime.date(2022, 1, 6), 10)
(datetime.date(2022, 1, 6), 11)
(datetime.date(2022, 1, 6), 12)
(datetime.date(2022, 1, 6), 13)
(datetime.date(2022, 1, 6), 14)
(datetime.date(2022, 1, 6), 15)
(datetime.date(2022, 1, 6), 16)
(datetime.date(2022, 1, 6), 17)
(datetime.date(2022, 1, 6), 18)
(datetime.date(2022, 1, 6), 19)
(datetime.date(2022, 1, 6), 20)
(datetime.date(2022, 1, 6), 21)
(datetime.date(2022, 1, 6), 22)
(datetime.date(2022, 1, 6), 23)
(datetime.date(2022, 1, 7), 0)
(datetime.date(2022, 1, 7), 1)
(datetime.date(2022, 1, 7), 2)
(datetime.date(2022, 1, 7), 3)
(datetime.date(2022, 1, 7), 4)
(datetime.date(2022, 1, 7), 5)
(datetime.date(2022, 1, 7), 6)
(datetime.date(2022, 1, 7), 7)
(datetime.date(2022, 1, 7), 8)
(datetime.date(2022, 1, 7), 9)
(datetime.date(2022, 1, 7), 10)
(datetime.date(2022, 1, 7), 11)
(datetime.date(2022, 1, 7), 12)
(datetime.date(2022, 1, 7), 13)
(datetime.date(2022, 1, 7), 14)
(datetime.date(2022, 1, 7), 15)
(datetime.date(2022, 1, 7), 16)
(datetime.date(2022, 1, 7), 17)
(datetime.date(2022, 1, 7), 18)
(datetime.date(2022, 1, 7), 19)
(datetime.date(2022, 1, 7), 20)
(datetime.date(2022, 1, 7), 21)
(datetime.date(2022, 1, 7), 22)
(datetime.date(2022, 1, 7), 23)
(datetime.date(2022, 1, 8), 0)
(datetime.date(2022, 1, 8), 1)
(datetime.date(2022, 1, 8), 2)
(datetime.date(2022, 1, 8), 3)
(datetime.date(2022, 1, 8), 4)
(datetime.date(2022, 1, 8), 5)
(datetime.date(2022, 1, 8), 6)
(datetime.date(2022, 1, 8), 7)
(datetime.date(2022, 1, 8), 8)
(datetime.date(2022, 1, 8), 9)
(datetime.date(2022, 1, 8), 10)
(datetime.date(2022, 1, 8), 11)
(datetime.date(2022, 1, 8), 12)
(datetime.date(2022, 1, 8), 13)
(datetime.date(2022, 1, 8), 14)
(datetime.date(2022, 1, 8), 15)
(datetime.date(2022, 1, 8), 16)
(datetime.date(2022, 1, 8), 17)
(datetime.date(2022, 1, 8), 18)
(datetime.date(2022, 1, 8), 19)
(datetime.date(2022, 1, 8), 20)
(datetime.date(2022, 1, 8), 21)
(datetime.date(2022, 1, 8), 22)
(datetime.date(2022, 1, 8), 23)
(datetime.date(2022, 1, 9), 0)
(datetime.date(2022, 1, 9), 1)
(datetime.date(2022, 1, 9), 2)
(datetime.date(2022, 1, 9), 3)
(datetime.date(2022, 1, 9), 4)
(datetime.date(2022, 1, 9), 5)
(datetime.date(2022, 1, 9), 6)
(datetime.date(2022, 1, 9), 7)
(datetime.date(2022, 1, 9), 8)
(datetime.date(2022, 1, 9), 9)
(datetime.date(2022, 1, 9), 10)
(datetime.date(2022, 1, 9), 11)
(datetime.date(2022, 1, 9), 12)
(datetime.date(2022, 1, 9), 13)
(datetime.date(2022, 1, 9), 14)
(datetime.date(2022, 1, 9), 15)
(datetime.date(2022, 1, 9), 16)
(datetime.date(2022, 1, 9), 17)
(datetime.date(2022, 1, 9), 18)
(datetime.date(2022, 1, 9), 19)
(datetime.date(2022, 1, 9), 20)
(datetime.date(2022, 1, 9), 21)
(datetime.date(2022, 1, 9), 22)
(datetime.date(2022, 1, 9), 23)
(datetime.date(2022, 1, 10), 0)
(datetime.date(2022, 1, 10), 1)
(datetime.date(2022, 1, 10), 2)
(datetime.date(2022, 1, 10), 3)
(datetime.date(2022, 1, 10), 4)
(datetime.date(2022, 1, 10), 5)
(datetime.date(2022, 1, 10), 6)
(datetime.date(2022, 1, 10), 7)
(datetime.date(2022, 1, 10), 8)
(datetime.date(2022, 1, 10), 9)
(datetime.date(2022, 1, 10), 10)
(datetime.date(2022, 1, 10), 11)
(datetime.date(2022, 1, 10), 12)
(datetime.date(2022, 1, 10), 13)
(datetime.date(2022, 1, 10), 14)
(datetime.date(2022, 1, 10), 15)
(datetime.date(2022, 1, 10), 16)
(datetime.date(2022, 1, 10), 17)
(datetime.date(2022, 1, 10), 18)
(datetime.date(2022, 1, 10), 19)
(datetime.date(2022, 1, 10), 20)
(datetime.date(2022, 1, 10), 21)
(datetime.date(2022, 1, 10), 22)
(datetime.date(2022, 1, 10), 23)
(datetime.date(2022, 1, 11), 0)
(datetime.date(2022, 1, 11), 1)
(datetime.date(2022, 1, 11), 2)
(datetime.date(2022, 1, 11), 3)
(datetime.date(2022, 1, 11), 4)
(datetime.date(2022, 1, 11), 5)
(datetime.date(2022, 1, 11), 6)
(datetime.date(2022, 1, 11), 7)
(datetime.date(2022, 1, 11), 8)
(datetime.date(2022, 1, 11), 9)
(datetime.date(2022, 1, 11), 10)
(datetime.date(2022, 1, 11), 11)
(datetime.date(2022, 1, 11), 12)
(datetime.date(2022, 1, 11), 13)
(datetime.date(2022, 1, 11), 14)
(datetime.date(2022, 1, 11), 15)
(datetime.date(2022, 1, 11), 16)
(datetime.date(2022, 1, 11), 17)
(datetime.date(2022, 1, 11), 18)
(datetime.date(2022, 1, 11), 19)
(datetime.date(2022, 1, 11), 20)
(datetime.date(2022, 1, 11), 21)
(datetime.date(2022, 1, 11), 22)
(datetime.date(2022, 1, 11), 23)
(datetime.date(2022, 1, 12), 0)
(datetime.date(2022, 1, 12), 1)
(datetime.date(2022, 1, 12), 2)
(datetime.date(2022, 1, 12), 3)
(datetime.date(2022, 1, 12), 4)
(datetime.date(2022, 1, 12), 5)
(datetime.date(2022, 1, 12), 6)
(datetime.date(2022, 1, 12), 7)
(datetime.date(2022, 1, 12), 8)
(datetime.date(2022, 1, 12), 9)
(datetime.date(2022, 1, 12), 10)
(datetime.date(2022, 1, 12), 11)
(datetime.date(2022, 1, 12), 12)
(datetime.date(2022, 1, 12), 13)
(datetime.date(2022, 1, 12), 14)
(datetime.date(2022, 1, 12), 15)
(datetime.date(2022, 1, 12), 16)
(datetime.date(2022, 1, 12), 17)
(datetime.date(2022, 1, 12), 18)
(datetime.date(2022, 1, 12), 19)
(datetime.date(2022, 1, 12), 20)
(datetime.date(2022, 1, 12), 21)
(datetime.date(2022, 1, 12), 22)
(datetime.date(2022, 1, 12), 23)
(datetime.date(2022, 1, 13), 0)
(datetime.date(2022, 1, 13), 1)
(datetime.date(2022, 1, 13), 2)
(datetime.date(2022, 1, 13), 3)
(datetime.date(2022, 1, 13), 4)
(datetime.date(2022, 1, 13), 5)
(datetime.date(2022, 1, 13), 6)
(datetime.date(2022, 1, 13), 7)
(datetime.date(2022, 1, 13), 8)
(datetime.date(2022, 1, 13), 9)
(datetime.date(2022, 1, 13), 10)
(datetime.date(2022, 1, 13), 11)
(datetime.date(2022, 1, 13), 12)
(datetime.date(2022, 1, 13), 13)
(datetime.date(2022, 1, 13), 14)
(datetime.date(2022, 1, 13), 15)
(datetime.date(2022, 1, 13), 16)
(datetime.date(2022, 1, 13), 17)
(datetime.date(2022, 1, 13), 18)
(datetime.date(2022, 1, 13), 19)
(datetime.date(2022, 1, 13), 20)
(datetime.date(2022, 1, 13), 21)
(datetime.date(2022, 1, 13), 22)
(datetime.date(2022, 1, 13), 23)
(datetime.date(2022, 1, 14), 0)
(datetime.date(2022, 1, 14), 1)
(datetime.date(2022, 1, 14), 2)
(datetime.date(2022, 1, 14), 3)
(datetime.date(2022, 1, 14), 4)
(datetime.date(2022, 1, 14), 5)
(datetime.date(2022, 1, 14), 6)
(datetime.date(2022, 1, 14), 7)
(datetime.date(2022, 1, 14), 8)
(datetime.date(2022, 1, 14), 9)
(datetime.date(2022, 1, 14), 10)
(datetime.date(2022, 1, 14), 11)
(datetime.date(2022, 1, 14), 12)
(datetime.date(2022, 1, 14), 13)
(datetime.date(2022, 1, 14), 14)
(datetime.date(2022, 1, 14), 15)
(datetime.date(2022, 1, 14), 16)
(datetime.date(2022, 1, 14), 17)
(datetime.date(2022, 1, 14), 18)
(datetime.date(2022, 1, 14), 19)
(datetime.date(2022, 1, 14), 20)
(datetime.date(2022, 1, 14), 21)
(datetime.date(2022, 1, 14), 22)
(datetime.date(2022, 1, 14), 23)

In [14]:
import pickle
with open('../data/processed data/all_od_tiny.pkl', 'wb') as f:
    pickle.dump(od_adj, f)

In [15]:
with open('../data/processed data/all_od_tiny.pkl', 'rb') as f1:
    data=pickle.load(f1)

In [16]:
data[(pd.to_datetime('2022-01-01').date(),12)]

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 3.]])

In [27]:
def is_cross_day_hour_tail(hour):
  if hour >= 0 and hour <=6:
    return True
  else:
    return False
    
def is_cross_day_hour_head(hour):
  if hour >= 18 and hour <=23:
    return True
  else:
    return False

In [37]:
def get_cross_day_emb(t): 
  weekends = [6,7]
  cd1 = cd2 = cd3 = 0
  if is_cross_day_hour_head(t[1]):
    cd3 = 1
    if t[0].weekday()+1 in weekends:
      cd1 = 1
      if t[0].weekday()+1 == 6:
        cd2 = 1
  elif is_cross_day_hour_tail(t[1]):
    cd3 = 1
    if t[0].weekday()+1 in weekends:
      cd2 = 1
      if t[0].weekday()+1 == 7:
        cd1 = 1
  return np.array([cd1,cd2,cd3])

In [17]:
get_cross_day_emb((pd.to_datetime('2022-01-03').date(),19))

1 0 0 1

In [22]:
d_w_list = [1,2,3,4,5,6,7]
one_hot_encoding = np.eye(len(d_w_list))
one_hot_encoding

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [46]:
def t_emb(t):
  d_w_list = range(1,8) # day of  week
  d_w_oh_list = np.eye(len(d_w_list)) # one hot
  d_w_emb = d_w_oh_list[d_w_list.index(t[0].weekday()+1)] # day of week embedding
  h_d_list = range(0,24) # hour of day
  h_d_oh_list = np.eye(len(h_d_list)) # one hot
  h_d_emb = h_d_oh_list[h_d_list.index(t[1])]
  cd_emb = get_cross_day_emb(t)
  emb = np.hstack((d_w_emb,h_d_emb,cd_emb))
  return emb

In [47]:
t_emb((pd.to_datetime('2022-01-03').date(),19))

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1.])